import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Playlists from '../components/playlists.js'
import AlbumArt from '../components/albumArt.js'
import ControlBar from '../components/controlBar.js'
import ArtistColumn from '../components/artistColumn.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Playlists className="item"></Playlists>
        <AlbumArt></AlbumArt>

        <ControlBar className="middle"></ControlBar>
        <ArtistColumn className="item"></ArtistColumn>
      </div>

      )
}
